version: '3.4'

services:

  beforethescholarship_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd 
    ports:
      - "5432:5432"
    networks:
      - beforethescholarship_network
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  beforethescholarship_api:
    ports:
      - "7000:80"
    networks:
      - beforethescholarship_network
    env_file:
      - env.api

  beforethescholarship_emailworker:
    networks:
      - beforethescholarship_network
    env_file:
      - env.emailworker

  beforethescholarship_identity:
    ports:
      - "7001:80"
    networks:
      - beforethescholarship_network
    env_file:
      - env.identityserver

  beforethescholarship_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - beforethescholarship_network
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  beforethescholarship_redis:
    ports:
      - '6379:6379'
    volumes:      
      - ~/.docker-conf/redis/data/:/data
    networks:
      - beforethescholarship_network

  beforethescholarship_web:
    ports:
      - "7002:80"
    networks:
      - beforethescholarship_network

networks:
  beforethescholarship_network:
    name: beforethescholarship
    driver: bridge
