version: '3.4'

secrets:
  emailusername:
    file: emailusername.txt
  emailpassword:
    file: emailpassword.txt
  clientsecret:
    file: clientsecret.txt

services:
  
  beforethescholarship_postgresql:
    image: postgres:15.1

  beforethescholarship_rabbitmq:
    image: beforethescholarshiprabbitmq:management
    build:
      context: .
      dockerfile: Systems/Api/BeforeTheScholarship.Api/Configuration/RabbitMqSetup/Dockerfile
    environment:
      - TZ=Europe/Moscow
  
  beforethescholarship_redis:
    image: redis

  beforethescholarship_api:
    image: ${DOCKER_REGISTRY-}beforethescholarshipapi
    build:
      context: .
      dockerfile: Systems/Api/BeforeTheScholarship.Api/Dockerfile
    depends_on:
      - beforethescholarship_postgresql
      - beforethescholarship_rabbitmq
    environment:
      - TZ=Europe/Moscow
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    secrets:
      - emailusername
      - emailpassword

  beforethescholarship_emailworker:
    image: ${DOCKER_REGISTRY-}beforethescholarshipemailworkers
    build:
      context: .
      dockerfile: Systems/Workers/BeforeTheScholarship.EmailWorker/Dockerfile
    depends_on:
      - beforethescholarship_postgresql
      - beforethescholarship_api
      - beforethescholarship_rabbitmq
    environment:
      - TZ=Europe/Moscow
    secrets:
      - emailusername
      - emailpassword

  beforethescholarship_identity:
    image: ${DOCKER_REGISTRY-}beforethescholarshipidentityserver
    build:
      context: .
      dockerfile: Systems/IdentityServer4/BeforeTheScholarship.IdentityServer/Dockerfile
    depends_on:
      - beforethescholarship_postgresql
      - beforethescholarship_api
    environment:
      - TZ=Europe/Moscow
    secrets:
      - clientsecret
